// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

export const ODHActivityPoi = {
    WELLNESS: 1,
    WINTER: 2,
    SUMMER: 4, 
    CULTURE: 8,
    OTHER: 16,
    GASTRONOMY: 32,
    MOBILITY: 64,
    SHOPSANDSERVICES: 128,
    ALL: 255,
}

export const LTSActivityType = {
    MOUNTAINS: 1,
    CYCLING: 2,
    LOCALTOURS: 4,
    HORSES: 8,
    HIKING: 16,
    RUNNINGANDFITNESS: 32,
    CROSSCOUNTRYSKITRACK: 64,
    TOBBOGANRUN: 128,
    SLOPES: 256,
    LIFTS: 512,
    ALL: 1023,
}

export const LTSPoiType = {
    DOCTORPHARMACIES: 1,
    SHOPS: 2,
    CULTUREANDSIGHTS: 4,
    NIGTHLIFEANDENTERTAINMENT: 8,
    PUBLICINSTITUTIONS: 16,
    SPORTSANDLEISURE: 32,
    TRAFFICANDTRANSPORT: 64,
    SERVICEPROVIDERS: 128,
    CRAFT: 256,
    ASSOCIATIONS: 512,
    COMPANIES: 1024,
    ALL: 2047,
}
